name = "RobustLCS"
version = "0.1.0"
keywords = ["math", "quantum"]
defaultTargets = ["RobustLCS"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[lean_lib]]
name = "RobustLCS"
